# for Microsoft Windows only
ARCHITECTURE=i686
CC=$(ARCHITECTURE)-pc-mingw32-gcc
CC_CONF+=-DCROSS_COMPILER_WIN32 -D_WIN32_
OBJ+=version.res
OUT=bce.exe
RES=$(ARCHITECTURE)-pc-mingw32-windres
INSTALLER=install-invalid.sh

