# for GNU/Linux, FreeBSD, OpenBSD, NetBSD, MacOSX, Solaris, openSolaris, AIX, HP-UNIX, MINIX, and other UNIX-based or UNIX-like systems.
CC=cc
# for Debug:
# CC_CONF+=-ggdb3
OUT=bcsh
RES=./version-invalid.sh
INSTALLER=install.sh

